author = "harumasa"
baseURL = "https://harumasa.github.io/github_pages/"
copyright = "harumasa All rights reserved."
languageCode = "ja"
publishDir = "docs"
theme = "hugo-book-master"
title = "harumasa.txt"
uglyurls = true

[params]
github = "https://github.com/harumasa/"
logo = "./images/logo.jpg"
